"""init auth module

Revision ID: 0515e497c271
Revises: 
Create Date: 2026-04-04 14:51:26.204164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0515e497c271'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS auth"))
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS core"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='auth'
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('company_limits',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('monthly_quota', sa.Integer(), nullable=False),
    sa.Column('current_month_usage', sa.Integer(), nullable=False),
    sa.Column('last_reset_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    schema='auth'
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('encrypted_last_name', sa.Text(), nullable=False),
    sa.Column('encrypted_first_name', sa.Text(), nullable=False),
    sa.Column('encrypted_patronymic', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('universities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.execute("CREATE TYPE core.diploma_status AS ENUM ('VALID', 'REVOKED')")
    op.create_table('diplomas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('last_name_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name_hash', sa.String(length=255), nullable=False),
    sa.Column('patronymic_hash', sa.String(length=255), nullable=True),
    sa.Column('diploma_number_hash', sa.String(length=255), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('digital_signature', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('VALID', 'REVOKED', name='diploma_status', schema='core', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'diploma_number_hash', name='uq_university_diploma_number'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diplomas', schema='core')
    op.execute("DROP TYPE core.diploma_status")
    op.drop_table('universities', schema='auth')
    op.drop_table('students', schema='auth')
    op.drop_table('company_limits', schema='auth')
    op.drop_table('companies', schema='auth')
    op.drop_table('api_keys', schema='auth')
    op.execute(sa.text("DROP SCHEMA IF EXISTS auth CASCADE"))
    op.execute(sa.text("DROP SCHEMA IF EXISTS core CASCADE"))
    # ### end Alembic commands ###
